### ISSUE TITLE
About the WTFPL (just letting you know)

### ISSUE THREAD

**Issue by MichaelAgarkov** [zulc22/800bros#1]
The WTFPL doesn't have any disclaimers **at all**, so people actually have the ability to make you liable for any damage this program can cause. Not to say you have to replace it, just as information.

**Comment by zulc22** [comment]
thanks for the info, i wasn't aware. i'll relicense with the unlicense which does have a disclaimer

**Comment by MichaelAgarkov** [comment]
The BSD 0-Clause License is shorter than the unlicense and has the same legal effect, again, as information

**Comment by MichaelAgarkov** [comment]
The BSD 0-Clause License is shorter than the unlicense and has the same legal effect, again, as information.
